apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: fibonacci-api
          image: xbumasa/fibonacci-api
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGHOST
              value: pg-cluster-service
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: posgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsecret
                  key: PGPASSWORD



